version: '3.4'
services:
  # # ELK
  # elk:
  #   image: sebp/elk
  #   container_name: elk_container_test
  #   ports:
  #     - "5601:5601"
  #     - "9200:9200"
  #     - "5044:5044"
  #   volumes:
  #   - ./data/elk:/var/lib/elasticsearch

  elasticsearch:
    image: elasticsearch:6.8.1
    container_name: elasticsearch_container
    environment:
    - discovery.type=single-node
    #- cluster.name=docker-cluster
    #- bootstrap.memory_lock=true
    #- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    volumes:
    - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    - 9300:9300
    # networks:
    # - esnet

  kibana:
    image: kibana:6.8.1
    container_name: kibana_container
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:6.8.1
    container_name: logstash_container
    volumes:
    - ./logstash/pipeline:/usr/share/logstash/pipeline
    - ./data/logstash:/mnt
    depends_on:
    - elasticsearch
    ports:
    - 5044:5044
    - 9600:9600
    - 5959:5959/udp

  filebeat:
    image: prima/filebeat
    volumes:
    - ./filebeat/filebeat.yml:/filebeat.yml
    - ./data/logs:/var/log
    depends_on:
    - logstash
  
  # Servico de Redis
  redis:
    build: ./redis
    container_name: redis_container
    image: redis_image
    logging:
      driver: syslog
      options:
        syslog-address: udp://127.0.0.1:514
    ports:
    - 6379:6379
    depends_on:
    - syslog-ng
    volumes:
    - ./data/redis:/data
    #- redis_data_desenv:/data #volume mapeado para o volume docker

  # WEB 
  nginx:
    container_name: nginx_container
    image: nginx
    depends_on:
    - syslog-ng
    logging:
      driver: syslog
      options:
        syslog-address: udp://127.0.0.1:514
    volumes:
    - /home/nfs_dsk/data:/usr/share/nginx/html
    #- ./nginx/content:/usr/share/nginx/html
    - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
    - 5080:80  

  # Syslog
  syslog-ng:
    build: ./syslog
    image: balabit_syslog-ng
    container_name: syslog-ng-teste
    # depends_on:
    # - elasticsearch
    ports:
    - 514:514/udp
    - 601:601/tcp
    - 6514:6514/tcp
    volumes:
    - ./data/logs:/var/log

  # Servico de syslog simples, testar com logger -n 127.0.0.1 -P 514 "Test message"
  # rsyslog:
  #   build: ./rsyslog
  #   container_name: rsyslog_container_test
  #   image: rsyslog_imagem
  #   environment:
  #   - "TZ=America/Sao_Paulo" # (-03, -0300)
  #   ports:
  #   - 514:514/udp
  #   volumes:
  #   - ./data/logs:/var/log
  #   #- ./rsyslog/rsyslog.d:/etc/rsyslog.d

  #Servico de NFS 
  # NFS:
  #   container_name: nfs_container
  #   #build: ./nfs
  #   #image: nfs_testez1
  #   image: itsthenetwork/nfs-server-alpine:latest
  #   privileged: true
  #   ports:
  #   - "2049:2049"
  #   volumes:
  #   - ./data/nfs_volume:/nfsshare
  #   environment:
  #   - SHARED_DIRECTORY=/nfsshare

  # mysql:
  #   container_name: mysql_container
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: testez1
  #     MYSQL_ROOT_PASSWORD: Zaq12wsX
  #   depends_on:
  #   - rsyslog
  #   logging:
  #     driver: syslog
  #     options:
  #       syslog-address: udp://127.0.0.1:514
  #   ports:
  #   - 3306:3306
  #   volumes:
  #   - ./data/mysql:/var/lib/mysql

  # #Servico de npm privado
  # sinopia:
  #   image: keyvanfatehi/sinopia:latest
  #   container_name: sinopia_container
  #   depends_on:
  #   - rsyslog
  #   logging:
  #     driver: syslog
  #     options:
  #       syslog-address: udp://127.0.0.1:514
  #   ports: 
  #   - "4873:4873"
  #   volumes:
  #   - ./data/sinopia:/opt/sinopia/storage
  #   - ./sinopia/config.yaml:/opt/sinopia/config.yaml

  # #Banco de dados NoSQL MongoDB
  # mongodb:
  #   image: mongo
  #   container_name: mongodb_container
  #   hostname: "mongo01"
  #   logging:
  #     driver: "syslog"
  #     options:
  #       syslog-address: "udp://127.0.0.1:514"
  #   depends_on:
  #   - "rsyslog"
  #   ports:
  #   - 27017:27017
  #   labels:
  #     NAME: "mongo01"
  #   volumes:
  #   #- mongo_data_desenv:/data/db
  #   - ./data/mongo:/data/db

# volumes:  
#   redis_data_desenv:
#   mongo_data_desenv:
  # nfs_redis:
  #   driver_opts:
  #     type: nfs
  #     o: addr=192.168.11.22,rw
  #     device: ":/home/desenv/disco"

# networks:
#   development-network:
#     driver: bridge

#   coletividade-borg-network: # esconde maquina internamente
#     internal: true
#     # ipam:
#     #   config:
#     #   - subnet: 10.0.0.0/8
#       #- subnet: 172.16.238.0/24
#       #- subnet: 2001:3984:3989::/64
