version: '3.4'
services:
  # ELK
  elk:
    image: sebp/elk
    container_name: sebp_elk_container
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044
      - 5959:5959/udp
    volumes:
    - ./elk/logstash:/etc/logstash/conf.d
    - ./data/elk:/var/lib/elasticsearch
    networks:
      devnet1:
        ipv4_address: 192.168.9.10

  filebeat:
    image: prima/filebeat
    volumes:
    - ./elk/filebeat/filebeat.yml:/filebeat.yml
    - ./data/logs:/var/log
    depends_on:
    - elk
    networks:
      devnet1:
        ipv4_address: 192.168.9.11
  
  # Servico de Redis
  redis:
    build: ./redis
    container_name: redis_container
    image: redis_image
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: udp://127.0.0.1:514
    # depends_on:
    # - syslog-ng
    ports:
    - 6379:6379
    volumes:
    - ./data/redis:/data
    #- redis_data_desenv:/data #volume mapeado para o volume docker
    networks:
      devnet1:
        ipv4_address: 192.168.9.12

  # WEB 
  nginx:
    container_name: nginx_container
    image: nginx
    # depends_on:
    # - syslog-ng
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: udp://127.0.0.1:514
    volumes:
    #- /home/nfs_dsk/data:/usr/share/nginx/html
    - ./nginx/content:/usr/share/nginx/html
    - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
    - 5080:80  
    networks:
      devnet1:
        ipv4_address: 192.168.9.13

  # # Syslog
  # syslog-ng:
  #   build: ./syslog
  #   image: balabit_syslog-ng
  #   container_name: syslog-ng-teste
  #   # depends_on:
  #   # - logstash
  #   ports:
  #   - 514:514/udp
  #   - 601:601/tcp
  #   - 6514:6514/tcp
  #   volumes:
  #   - ./data/logs:/var/log
  #   networks:
  #     devnet1:
  #       ipv4_address: 192.168.9.14

  # #Servico de NFS 
  # NFS:
  #   container_name: nfs_container
  #   #build: ./nfs
  #   #image: nfs_testez1
  #   image: itsthenetwork/nfs-server-alpine:latest
  #   privileged: true
  #   ports:
  #   - "2049:2049"
  #   volumes:
  #   - ./data/nfs_volume:/nfsshare
  #   environment:
  #   - SHARED_DIRECTORY=/nfsshare
  # #   networks:
  # #     devnet1:
  # #       ipv4_address: 192.168.9.15

  # mysql:
  #   container_name: mysql_container
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: testez1
  #     MYSQL_ROOT_PASSWORD: Zaq12wsX
  #   depends_on:
  #   - rsyslog
  #   logging:
  #     driver: syslog
  #     options:
  #       syslog-address: udp://127.0.0.1:514
  #   ports:
  #   - 3306:3306
  #   volumes:
  #   - ./data/mysql:/var/lib/mysql
  #   networks:
  #     devnet1:
  #       ipv4_address: 192.168.9.16

  # #Banco de dados NoSQL MongoDB
  # mongodb:
  #   image: mongo
  #   container_name: mongodb_container
  #   hostname: "mongo01"
  #   logging:
  #     driver: "syslog"
  #     options:
  #       syslog-address: "udp://127.0.0.1:514"
  #   depends_on:
  #   - "rsyslog"
  #   ports:
  #   - 27017:27017
  #   labels:
  #     NAME: "mongo01"
  #   volumes:
  #   #- mongo_data_desenv:/data/db
  #   - ./data/mongo:/data/db
  #   networks:
  #     devnet1:
  #       ipv4_address: 192.168.9.17

  simplepypi:
    build: ./simplepypi
    container_name: simplepypi_container
    image: simplepypi_image
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: udp://127.0.0.1:514
    # depends_on:
    # - syslog-ng
    ports:
    - 8000:8000
    #volumes:
    #- ./data/redis:/data
    #- redis_data_desenv:/data #volume mapeado para o volume docker
    networks:
      devnet1:
        ipv4_address: 192.168.9.18

# volumes:  
#   redis_data_desenv:
#   mongo_data_desenv:
  # nfs_redis:
  #   driver_opts:
  #     type: nfs
  #     o: addr=192.168.11.22,rw
  #     device: ":/home/desenv/disco"

networks:
  devnet1:
    ipam:
      driver: default
      config:
      - subnet: "192.168.9.0/24"
        # gateway: 192.168.9.254

  # development-network:
  #   driver: bridge
