version: '3'
services:
  # # Servico composto nginx-nfs
  # composto:
  #   build: ./composto
  #   container_name: composto_nginx_nfs_container
  #   image: img_ubuntu_nginx_nfs
  #   privileged: true
  #   ports:
  #   - 8080:8080
  #   - 2049:2049
  #   volumes:
  #   - ./composto/share_file:/usr/share/nginx/html
  
  # Servico de Redis
  redis:
    build: ./redis
    container_name: redis_container
    image: redis_image
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
    ports:
    - "6379:6379"
    #networks:
    #- development-network
    depends_on:
    - "rsyslog"
    volumes:
    - redis_data_desenv:/data

  #Servico de NFS 
  # NFS:
  #   container_name: nfs_container
  #   #build: ./nfs
  #   #image: nfs_testez1
  #   image: itsthenetwork/nfs-server-alpine:latest
  #   privileged: true
  #   ports:
  #   - "2049:2049"
  #   volumes:
  #   - ./nfs/share_nfs:/nfsshare
  #   environment:
  #   - SHARED_DIRECTORY=/nfsshare

  # #Servico web 
  # nginx:
  #   container_name: nginx_container
  #   image: nginx
  #   volumes:
  #   - ./nginx/content:/usr/share/nginx/html
  #   ports:
  #   - "8080:80"

  #Servico de npm privado
  sinopia:
    image: keyvanfatehi/sinopia:latest
    container_name: sinopia_container
    ports: 
    - "4873:4873"
    volumes:
    - ./sinopia/storage:/opt/sinopia/storage
    - ./sinopia/etc/config.yaml:/opt/sinopia/config.yaml

  # #Banco de dados NoSQL MongoDB
  # mongodb:
  #   image: mongo
  #   container_name: mongodb_container
  #   hostname: "mongo01"
  #   logging:
  #     driver: "syslog"
  #     options:
  #       syslog-address: "udp://127.0.0.1:514"
  #   depends_on:
  #   - "rsyslog"
  #   ports:
  #   - 27017:27017
  #   labels:
  #     NAME: "mongo01"
  #   volumes:
  #   - mongo_data_desenv:/data/db
  #   #- ./mongo/data/:/data/db

  # #servico de Syslog Unix
  # syslog:
  #   container_name: syslog_container
  #   image: balabit/syslog-ng
  #   ports:
  #   - "601:601"
  #   - "514:514"
  #   volumes:
  #   - ./syslog/conf/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
  #   - ./syslog/logs:/var/log

  # Servico de syslog simples, testar com logger -n 127.0.0.1 -P 514 "Test message"
  rsyslog:
    build: ./rsyslog
    container_name: rsyslog_container
    image: img_rsyslog
    ports:
    - 514:514/udp
    volumes:
    - ./rsyslog/log:/var/log
    - ./rsyslog/rsyslog.d:/etc/rsyslog.d

volumes:  
  redis_data_desenv:
  mongo_data_desenv:
  #./redis/data

# networks:
#   development-network:
#     driver: bridge

#   app_net:
#     driver: bridge
#     enable_ipv6: true
#     external: true
#     ipam:
#       driver: default
#       config:
#       - subnet: 172.16.238.0/24
#       - subnet: 2001:3984:3989::/64