version: '3.4'
services:
  # Servico de syslog simples, testar com logger -n 127.0.0.1 -P 514 "Test message"
  rsyslog:
    build: ./rsyslog
    container_name: rsyslog_container
    image: img_rsyslog
    ports:
    - 514:514/udp
    volumes:
    - ./rsyslog/log:/var/log
    - ./rsyslog/rsyslog.d:/etc/rsyslog.d
  
  # Servico de Redis
  redis:
    build: ./redis
    container_name: redis_container
    image: redis_image
    logging:
      driver: syslog
      options:
        syslog-address: udp://127.0.0.1:514
    ports:
    - 6379:6379
    # networks:
    # - development-network
    depends_on:
    - rsyslog
    volumes:
    # - type: volume #volume mapeado em NFS
    #   source: nfs_redis
    #   target: /data
    #   volume:
    #     nocopy: true
    #- redis_data_desenv:/data #volume mapeado para o volume docker
    - ./redis/data:/data #volume mapeado para o disco local

  # #Servico web 
  nginx:
    container_name: nginx_container
    image: nginx
    depends_on:
    - rsyslog
    logging:
      driver: syslog
      options:
        syslog-address: udp://127.0.0.1:514
    volumes:
    - /home/nfs_dsk/data:/usr/share/nginx/html
    - ./etc/nginx/conf.d:/etc/nginx/conf.d
            

    #- ./nginx/content:/usr/share/nginx/html
    #- ~/Projetos/SCrappAmil/data/pdfs:/usr/share/nginx/html

    # configs: # para usar executar: docker config create nginx-config etc/nginx.conf
    #   - source: nginx-config
    #     target: /etc/nginx/conf.d/default.conf
    ports:
    - 5080:80

  # mysql:
  #   container_name: mysql_container
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: testez1
  #     MYSQL_ROOT_PASSWORD: Zaq12wsX
  #   depends_on:
  #   - rsyslog
  #   logging:
  #     driver: syslog
  #     options:
  #       syslog-address: udp://127.0.0.1:514
  #   ports:
  #   - 3306:3306
  #   volumes:
  #   - ./mysql/db:/var/lib/mysql

  # #Servico de npm privado
  # sinopia:
  #   image: keyvanfatehi/sinopia:latest
  #   container_name: sinopia_container
  #   depends_on:
  #   - rsyslog
  #   logging:
  #     driver: syslog
  #     options:
  #       syslog-address: udp://127.0.0.1:514
  #   ports: 
  #   - "4873:4873"
  #   volumes:
  #   - ./sinopia/storage:/opt/sinopia/storage
  #   - ./sinopia/etc/config.yaml:/opt/sinopia/config.yaml

  # #Banco de dados NoSQL MongoDB
  # mongodb:
  #   image: mongo
  #   container_name: mongodb_container
  #   hostname: "mongo01"
  #   logging:
  #     driver: "syslog"
  #     options:
  #       syslog-address: "udp://127.0.0.1:514"
  #   depends_on:
  #   - "rsyslog"
  #   ports:
  #   - 27017:27017
  #   labels:
  #     NAME: "mongo01"
  #   volumes:
  #   - mongo_data_desenv:/data/db
  #   #- ./mongo/data/:/data/db

  #Servico de NFS 
  # NFS:
  #   container_name: nfs_container
  #   #build: ./nfs
  #   #image: nfs_testez1
  #   image: itsthenetwork/nfs-server-alpine:latest
  #   privileged: true
  #   ports:
  #   - "2049:2049"
  #   volumes:
  #   - ./nfs/share_nfs:/nfsshare
  #   environment:
  #   - SHARED_DIRECTORY=/nfsshare

  # #servico de Syslog Unix
  # syslog:
  #   container_name: syslog_container
  #   image: balabit/syslog-ng
  #   ports:
  #   - "601:601"
  #   - "514:514"
  #   volumes:
  #   - ./syslog/conf/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
  #   - ./syslog/logs:/var/log

  # # Servico composto nginx-nfs
  # composto:
  #   build: ./composto
  #   container_name: composto_nginx_nfs_container
  #   image: img_ubuntu_nginx_nfs
  #   privileged: true
  #   ports:
  #   - 8080:8080
  #   - 2049:2049
  #   volumes:
  #   - ./composto/share_file:/usr/share/nginx/html

volumes:  
  redis_data_desenv:
  mongo_data_desenv:
  # nfs_redis:
  #   driver_opts:
  #     type: nfs
  #     o: addr=192.168.11.22,rw
  #     device: ":/home/desenv/disco"

# networks:
#   development-network:
#     driver: bridge

#   coletividade-borg-network: # esconde maquina internamente
#     internal: true
#     # ipam:
#     #   config:
#     #   - subnet: 10.0.0.0/8
#       #- subnet: 172.16.238.0/24
#       #- subnet: 2001:3984:3989::/64
